version: '3.8'

services:
  web:
    build: ./services/web
    command: flask run -h 0.0.0.0
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

volumes:
  postgres_data: