"""initial migration

Revision ID: 446dc89cfa9b
Revises: 
Create Date: 2021-10-21 13:14:06.342623

"""
from alembic import op
import sqlalchemy as sa
from dbUtils import utcnow

# revision identifiers, used by Alembic.
revision = '446dc89cfa9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True, server_default=utcnow(), onupdate=utcnow()),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('steam_id', name=op.f('uq_players_steam_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    # ### end Alembic commands ###
